# D:\Social_Platform_Emulation\config\st_1sw.grid.yaml
# [Aligned] 时空仿真: 1层 小世界网络

# --- 1. 网络与地理位置统一配置 ---
network:
  num_nodes: 1000
  layers:
    - {type: small_world, params: {k: 10, beta: 0.1}}

  # 模式: grid (网格分布)
  position_distribution:
    type: 'grid'
    grid_params: {rows: 32, cols: 32, jitter: 0.02}

# --- 2. 仿真模型参数 ---
simulation_params:
  max_iterations: 400
  record_interval: 10

  convergence_params:
    enabled: true        # 开启功能
    threshold: 0.0001    # 总观点变化阈值
    patience: 100        # 连续100次低于阈值则停止

  initial_state: {opinion_range: [0.0, 1.0], epsilon_base: 0.15}
  dw_params: {mu: 0.2}
  
  coupling_params:
    enabled: false
    lambda: 0.01
    c_kl_global: 0.01

  spatiotemporal_params:
    poisson_rate: 0.1
    spatial_range: [[0.0, 1.0], [0.0, 1.0]]
    alpha: 0.8
    beta: 0.05
    interaction_prob: {base: 0.7, gain: 0.3}
    trust_scope: {gain: 0.15}
    learning_rate: {gain: 0.2}
