# config\st_5sw_5sf.multi_clustered.yaml
# [Aligned] 时空仿真: 10层 (5sw+5sf) 混合网络

# --- 1. 网络与地理位置统一配置 ---
network:
  num_nodes: 1000
  layers:
    - {type: small_world, params: {k: 10, beta: 0.1}}
    - {type: small_world, params: {k: 10, beta: 0.1}}
    - {type: small_world, params: {k: 10, beta: 0.1}}
    - {type: small_world, params: {k: 10, beta: 0.1}}
    - {type: small_world, params: {k: 10, beta: 0.1}}
    - {type: scale_free, params: {m: 3}}
    - {type: scale_free, params: {m: 3}}
    - {type: scale_free, params: {m: 3}}
    - {type: scale_free, params: {m: 3}}
    - {type: scale_free, params: {m: 3}}

  # 模式: multi_clustered (多核心)
  position_distribution:
    type: 'multi_clustered'
    hotspots: 
      - {center: [0.25, 0.25], radius: 0.2, ratio: 0.45}
      - {center: [0.75, 0.75], radius: 0.15, ratio: 0.35}

# --- 2. 仿真模型参数 ---
simulation_params:
  max_iterations: 400
  record_interval: 10

  convergence_params:
    enabled: true        # 开启功能
    threshold: 0.001    # 总观点变化阈值
    patience: 30        # 连续100次低于阈值则停止

  initial_state: {opinion_range: [0.0, 1.0], epsilon_base: 0.15}
  dw_params: {mu: 0.2}
  
  coupling_params:
    enabled: true
    lambda: 0.01
    c_kl_global: 0.01

  spatiotemporal_params:
    poisson_rate: 0.1
    spatial_range: [[0.0, 1.0], [0.0, 1.0]]
    alpha: 0.8
    beta: 0.05
    interaction_prob: {base: 0.7, gain: 0.3}
    trust_scope: {gain: 0.15}
    learning_rate: {gain: 0.2}
