# basic_1sw.yaml: 基础仿真，包含一个5000节点的小世界网络层
network:
  num_nodes: 1000
  layers:
    - {type: small_world, params: {k: 10, beta: 0.1}}

simulation_params:
  max_iterations: 400
  record_interval: 10

  convergence_params:
    enabled: true        # 开启功能
    threshold: 0.001    # 总观点变化阈值
    patience: 30        # 连续100次低于阈值则停止
  
  initial_state: 
    opinion_range: [0.0, 1.0]
    epsilon_base: 0.15
    
  dw_params: 
    mu: 0.2
    
  coupling_params: 
    enabled: false
    lambda: 0.01
    c_kl_global: 0.1