# test_spatiotemporal.yaml

# --- 1. 网络与地理位置统一配置 ---
network:
  num_nodes: 200
  layers:
    - {type: small_world, params: {k: 4, beta: 0.1}}
    - {type: scale_free, params: {m: 2}}
    - {type: random, params: {p: 0.0201005}}

  # 模式: gaussian (高斯分布)
  position_distribution:
    type: 'gaussian'
    gaussian_params: {mean: [0.5, 0.5], cov: [[0.03, 0], [0, 0.03]]}

# --- 2. 仿真模型参数 ---
simulation_params:
  max_iterations: 100
  record_interval: 10
  convergence_params:
    enabled: true
    threshold: 0.001
    patience: 20
  initial_state: {opinion_range: [0.0, 1.0], epsilon_base: 0.15}
  dw_params: {mu: 0.2}
  coupling_params:
    enabled: true
    lambda: 0.002
    c_kl_global: 0.002
  spatiotemporal_params:
    poisson_rate: 0.1
    spatial_range: [[0.0, 1.0], [0.0, 1.0]]
    alpha: 2
    beta: 0.04
    interaction_prob: {base: 0.4, gain: 0.5}
    trust_scope: {gain: 0.4}
    learning_rate: {gain: 0.3}

    spatial_neighbors:
      enabled: true          # 是否启用空间邻居发现
      base_radius: 0.02      # 节点的日常空间感知半径 (无事件影响时)
      radius_gain: 0.15       # 事件对空间感知半径的增益系数
    
